
codon_mapping = {
    "F": 2, "L": 6, "S": 6, "Y": 2, "C": 2, "W": 1,
    "P": 4, "H": 2, "Q": 2, "R": 6, "I": 3, "M": 1,
    "T": 4, "N": 2, "K": 2, "V": 4, "A": 4, "D": 2,
    "E": 2, "G": 4, "*": 3  # '*' represents the stop codon
}


protein_sequence = "MHYVAHAASVTWQYLPQCVKMIHDMFHNEVYNRPGQWYHKRPESCIDDTCFVTVKEFWRTRSLVAFITHTGRFIRSTVHTIAQYYEMEMLYNEYSTEKSEWITLYKDRWSQFQQPHWTDRWVAFCSHPHWVGVIPLYHRQAHCMLGTTRFITTYTHIVFQLGRCLDQFSRRPNLTFHDNLWHCHTQSLSVGVSMESWEQPRVWPHKRRHSKIYVNCGAFYLGPFDHNGIYVCIITWTTAWWDAKSRFVRINHRPKQNGQFLYVEGDDPKDNCGMAYLWTPLPDTKSNHGVSRQGKLCCKPYFLRDGVRWMVDFWGVCYIISKNNICYPQSATCMIFNAVFETVKWCWGIVNPWHKQMKYRRKNHARAPWPSYWNSICQTSHNFNSNVPKEFVADWLIRGWHKPVGGHSIWSDRWDWQLTRRDGEWMFCLNAKWTQQQCIQNIDPHWFAQHKSACQDECETLEDILVPAYWLYCLVSKYNKSNFQDGKLESADNHQMFTLPERDYCDNIHKAMRLQAFDGMHFRVFCMTNGMGHGPQHDFLVMKCHCRHIDQDFIPDQEQWNKMAEQAYILDVETQMDYQHVWFRWYGSPLQVEDQCDMGTQGFPVRRQAPAANMGHWIATGQSFWWILLKYMYDQANPDHPAARKAMRGTRWEHTDELEEVVGFISLQCARYASRDIAPEGFVPSPWFMCCSSKLNIRELVFDHWSKSQNPWDAMWKYNIGSNVWMYCKYAKVQDFTISKKTKFSPRRARLAYSACAMRCRLNEWQEEYHQMVHGDDAQPCVLPARYLATFPIMDIHREMVHTMINYKTISHGQSNIFEQQRYGRLNHCGWWQLEQFAKWFYYFGTMSQEPQFSPQDKDDCVDPNNADWQGGRRDSVWFWEQHSILGTTYVKVPNPAWSGPWNVWVQCNKEMRLHCRQQAMYAFALCQIPWKCWADICWEFYMIPWTPVCEGYRWCCCGKGNYEHLIYKMSHVWDTRCNQKRMIPWAYLSDIPAPAQ"

total_possibilities = 1
for aa in protein_sequence:
    total_possibilities *= codon_mapping[aa]

# Multiply by the number of stop codons and take modulo 1,000,000
total_possibilities *= 3
total_possibilities %= 1000000

print(total_possibilities)





