#Rosalind REVC
sequence3 = 'CGGCAGGCCAAGCCCGCGCCCGCGAGCCCCCACAACCAAAAGGGATTACCGCCATAATCTTTCTCGGATCCACCTGCGGCTTTTCCCTTCTGATTCACCACAGAGCGACACGTGGGATATGTAAACGTTCTGTTTGATAGATCTAAGTAAAGCTTCCCAAGTAATCTAAGGTGTTACTTGTGTATTACATCAAACCGAGACCCAAAGGGCAGGTGTGATAACAGATCGGTGTCCTTGTTCTTTCAAAAAACGCAATCTTATACCCATTCCTTGCGGAAGATCGGTTTCGGTGCAACGTTGACGCAAGATTACTTAATCGTTCTAAGGGCGGTTCAGCAGAAGATCCCCCAACCCAAAGATCTCGCTAGGCAGGTAGGCATGCAAGCGACGCGAATAGCGGAACGGGCAACGTCGGAGGGTACAGGGAGTATACGGGGTGCTTGTTGTTTGGGGACGCGAGATTCGGACAGCATTACGATTTACCTGGACTGACGGGCCAGCCCCCGCGTAAGTATTGGCGCAACCCCAGGGTATCTACACGAGCTAGGCCTTTCTGACAGGTGTGAAACGTGTCTAGATAGAAGAAGCACTCGACCATTGCCACCCGTTACATCAGTACTTTTAATGTAGCTTAGAATGGCCGATTGGCGGTGTGGGGACGACCACTTCTCGCCTCGACCGATGTGTTAGCCGTGCAGGTTGTAGGATCGAACCAACTTCCCACTGTCTGAACTGATCTTGAAAGCTCCACTCCGCCTCGCTTAGGGTCGAAGAACACTGGAATCCCAACCATTGTAGCGGCCGGTGGCCTCGGACTCGCAAGTACCTTAAAACAATGAAGTGTGGTATCGGGTACGCCAAAAATATTCTAAAGCCTCCGGTCGTAATGAAGTTGAGTTTTCGAATCAATCGTCTCTTTATGTTATGCGGTTTTGTACTATTCTTCGAGGGCAGAGGCTGAGTAATGCCCCAGAACATACTCGCCCTCAA'
complementary_sequence = ' '

for symbol in sequence3:
        if symbol == 'A':
                complementary_sequence += 'T'
        elif symbol == 'C':
                complementary_sequence += 'G'
        elif symbol == 'G':
                complementary_sequence += 'C'
        elif symbol == 'T':
                complementary_sequence += 'A'

print('complementary sequences: ' + complementary_sequence + '\n')
print('reversed: ' + complementary_sequence[::-1]